# serverless-compose.yml
services:
  aws-node-http-api-project:
    path: services/aws-node-http-api-project

  aws-node-scheduled-cron-project:
    path: services/aws-node-scheduled-cron-project

# All client applications after this line
  simple-vue-app:
    path: clients/simple-vue-app