service: simple-vue-app
frameworkVersion: '3'

custom:
  region: '${file(../../env.yml):${opt:stage}.region}'

provider:
  name: aws
  region: ${self:custom.region}
  # The S3 prefix under which deployed artifacts are stored (default: serverless)
  deploymentPrefix: serverless
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
    skipPolicySetup: true
    versioning: true